---
- name: Deploy Node.js App from DockerHub to Webservers
  hosts: webservers
  become: yes
  vars:
    # Provide your DockerHub username and image name.
    docker_image: "mahmud4550/my-app:latest"
    container_name: "nodeapp_container"

  tasks:
    # 1. Ensuring only python3-docker for the Ansible Docker module.
    - name: Ensure Python Docker SDK is installed
      apt:
        name: python3-docker
        state: present

    # 2. Ensure the latest image is pulled from DockerHub.
    - name: Pull latest image from DockerHub
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull
        force_source: yes

    # 3. Container Service Operation and Port Mapping
    - name: Run Node.js App Container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        hostname: "{{ inventory_hostname }}"
        restart_policy: always
        recreate: yes
        published_ports:
          - "3000:80"