[webservers]
app-server-1 ansible_host=192.168.123.11 ansible_user=appserver1
app-server-2 ansible_host=192.168.123.12 ansible_user=appserver2

[proxy]
nginx-proxy-server ansible_host=192.168.123.10 ansible_user=nginxproxyserver

[all:vars]
ansible_password=12345
ansible_sudo_pass=12345
ansible_ssh_common_args='-o StrictHostKeyChecking=no'